#!/usr/bin/env ruby
# frozen_string_literal: true

require "manageiq-floe"
require "optimist"

opts = Optimist.options do
  version "v#{ManageIQ::Floe::VERSION}\n"
  opt :workflow, "Path to your workflow json", :type => :string, :required => true
  opt :inputs, "JSON payload to input to the workflow", :type => :string, :default => '{}'
  opt :credentials, "JSON payload with credentials", :type => :string, :default => '{}'
end

require "logger"
ManageIQ::Floe.logger = Logger.new(STDOUT)

workflow = ManageIQ::Floe::Workflow.load(opts[:workflow], opts[:inputs], opts[:credentials])

output = workflow.run!

puts output.inspect
